sign_mode=internal
sign_file=false
sign_file_globalapk=false
sign_file_update=false
sign_key=testkey
donor_mode=release
provider=unknow
device=unknow
m_arch=unknow
m_cf=unknow
m_pmem=unknow
m_nc=unknow
m_os=Google Android
#SYSMODE=zip\normally for Normally SmartPhoen and Pad
#SYSMODE=bin\Allwinner for Allwinner Binaries Code Package
#SYSMODE=bin\RK28xx for Rock-Chips RK2816\RK2818
#SYSMODE=bin\RK29xxV1 for Rock-Chips RK29 Cramfs
#SYSMODE=bin\RK29xxV2 for Rock-Chips RK29 Ext4FS
def_config_sysmode=zip\Normally